---
- name: Verify
  hosts: all
  tasks:
    - name: Check if NGINX is installed
      ansible.builtin.package:
        name: nginx
        state: present
      check_mode: true
      register: install
      failed_when: (install is changed) or (install is failed)

    - name: Check if NGINX service is running
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true
      check_mode: true
      register: service
      failed_when: (service is changed) or (service is failed)

    - name: Verify NGINX is up and running
      ansible.builtin.uri:
        url: http://localhost
        status_code: 200
      when: ansible_facts['distribution'] not in ["Alpine", "SLES"]

    - name: Verify NGINX is up and running
      ansible.builtin.uri:
        url: http://localhost
        status_code: 404
      when: ansible_facts['distribution'] == 'Alpine'

    - name: Verify NGINX is up and running
      ansible.builtin.uri:
        url: http://localhost
        status_code: 403
      when: ansible_facts['distribution'] == 'SLES'
