---
- name: Converge
  hosts: all
  tasks:
    - name: Uninstall NGINX
      ansible.builtin.include_role:
        name: nginxinc.nginx
      vars:
        nginx_type: plus
        nginx_setup_license: false
        nginx_setup: uninstall
