---
# Copyright (C) 2020 Ties de Kock
# Copyright (C) 2023 Robert Wimmer
# SPDX-License-Identifier: GPL-3.0-or-later

- name: (Fedora) Install WireGuard packages
  ansible.builtin.yum:
    name:
      - "wireguard-tools"
    state: present
    update_cache: "{{ wireguard_update_cache }}"
