---
- name: reconfigure openssh-server
  become: true
  command: dpkg-reconfigure --frontend noninteractive openssh-server

- name: restart openssh-server
  become: true
  listen: "reconfigure openssh-server"
  service: name=ssh state=restarted

- name: reload systemd
  become: true
  command: systemctl daemon-reload

- name: restart ssh.socket
  become: true
  service: name=ssh.socket state=restarted enabled=yes
