---
ansible_become: true
wireguard_address: "10.2.0.1/32"
wireguard_port: "51820"
wireguard_private_key: "{{ vault_server.private_key }}"

wireguard_unmanaged_peers:
  lilith:
    allowed_ips: 10.2.0.10/32
    public_key: ic3N3ZCZrI26lJD9AyI+/vMHH859lOzh1BN0ogpIzB0=
    preshared_key: "{{ vault_preshared_keys.lilith }}"

  Polaris:
    allowed_ips: 10.2.0.20/32
    public_key: FuzMXMDySj9LlU1arkAGToNaBJHj1gZ9VecYSWo0NEg=
    preshared_key: "{{ vault_preshared_keys.Polaris }}"

  Iridium:
    allowed_ips: 10.2.0.21/32
    public_key: Knd5jtUfxZI6S9pSm2M8eRmkhNcl1pUJkPSNy5qFamg=
    preshared_key: "{{ vault_preshared_keys.Iridium }}"

  Rubidium:
    allowed_ips: 10.2.0.22/32
    public_key: V5pA03l7+aILJLpTxJpeBiOcn0RGrWXKirdygROWy0E=
    preshared_key: "{{ vault_preshared_keys.Rubidium }}"

  narishroom:
    allowed_ips: 10.2.0.100/32
    public_key: q5eZ+1lCBaPkl7ml+i3nPMXOBvHkWOLzC/5UYg6wQUI=
    preshared_key: "{{ vault_preshared_keys.narishroom }}"
