---
wireguard_address: "10.2.0.1/24"

wireguard_unmanaged_peers:
  lilith:
    allowed_ips: 10.2.0.10/32
    public_key: ic3N3ZCZrI26lJD9AyI+/vMHH859lOzh1BN0ogpIzB0=
    preshared_key: "{{ vault_preshared_keys.lilith }}"
  connor:
    allowed_ips: 10.2.0.11/32
    public_key: FuzMXMDySj9LlU1arkAGToNaBJHj1gZ9VecYSWo0NEg=
    preshared_key: "{{ vault_preshared_keys.connor }}"
