---
- import_tasks: apt-update.yml
  become: true
  tags: [upkeep]

- import_tasks: ssh-hardening.yml
  become: true
  tags: [ssh]

- import_tasks: ssh-regenerate.yml
  become: true
  tags: [ssh:regenerate, never]

- import_tasks: swapfile.yml
  become: true
  tags: [swap]
