---
- name: Wireguard server
  hosts: wireguard_servers
  roles:
    - githubixx.ansible_role_wireguard # https://github.com/githubixx/ansible-role-wireguard
  tasks:
    - name: Setup IPv4 forward
      ansible.posix.sysctl:
        name: net.ipv4.ip_forward
        value: 1
        sysctl_set: true
        state: present
        reload: true
